# Generated by Django 3.0.2 on 2020-01-20 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rayyith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='ID Card Number')),
                ('name', models.CharField(max_length=64, verbose_name='Rayyith Name')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Schedule Name')),
                ('due_on', models.IntegerField(verbose_name='Schedule Item Due (in weeks)')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_on', models.DateTimeField(verbose_name='Date Administered')),
                ('rayyith', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Rayyith')),
                ('schedule_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ScheduleItem')),
            ],
        ),
    ]
